import { featureTranslate as t } from "./featureTranslations";
import { useEffect,useState } from "react";
import { openUrl } from "@tauri-apps/plugin-opener";
import { Clipboard,Download,ExternalLink,LoaderCircle } from "lucide-react";
import { DataModal } from "./DataActions";
import { applicationIdentity,copySupportReport,saveSupportReport,supportReport,type SupportReport } from "./supportDiagnostics";
import { useLocale } from "./i18n";
import { errorText } from "./runtime";
import logo from "./assets/datapyn-logo.svg";
import "./supportDiagnostics.css";

export function AboutDialog({onClose,onMessage}:{onClose:()=>void;onMessage?:(message:string)=>void}) {
  useLocale();
  const [identity,setIdentity]=useState<{name:string;version:string}>(),[report,setReport]=useState<SupportReport>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void applicationIdentity().then(value=>{if(active)setIdentity(value);}).catch(()=>{if(active)setError(t("A versão do aplicativo está indisponível."));});void supportReport().then(value=>{if(active)setReport(value);}).catch(()=>{if(active)setError(t("O diagnóstico do runtime está indisponível."));});return()=>{active=false;};},[]);
  async function action(task:()=>Promise<unknown>,message:string){setBusy(true);setError("");try{const value=await task();if(value)onMessage?.(t(message));}catch(failure){setError(errorText(failure));}finally{setBusy(false);}}
  return <DataModal title={t("Sobre o DataPyn")} onClose={onClose}><div className="data-modal-body about-content"><div className="about-identity"><img src={logo} alt=""/><div><h2>{t("DataPyn")}</h2><p>{t("Versão")} {identity?.version??"…"}</p><span>{t("Análise SQL e Python em um aplicativo desktop.")}</span></div></div><div className="about-platform"><section><h3>{t("Interface")}</h3><p>{t("Tauri · React · Monaco · Dockview · Plotly")}</p><small>{t("React, Monaco, Dockview e Plotly: MIT. Tauri: MIT / Apache-2.0.")}</small></section><section><h3>{t("Bancos")}</h3><p>{t("SQL Server · PostgreSQL · MySQL · MariaDB · SQLite · Databricks")}</p></section></div><p className="about-license">{t("Licença do DataPyn: MIT")}</p><div className="about-links"><button onClick={()=>void action(()=>openUrl("https://github.com/natharuc/datapyn"),"")}><ExternalLink size={12}/>{t("github.com/natharuc/datapyn")}</button><button onClick={()=>void action(()=>openUrl("https://datapyn.com"),"")}><ExternalLink size={12}/>{t("datapyn.com")}</button></div><details className="about-runtime"><summary>{t("Runtime e bibliotecas")}</summary>{report?<><dl><div><dt>{t("Python")}</dt><dd>{report.runtime.python} {t("·")} {report.runtime.implementation}</dd></div><div><dt>{t("Sistema")}</dt><dd>{report.system.os} {report.system.os_release} {t("·")} {report.system.architecture}</dd></div><div><dt>{t("Protocolo")}</dt><dd>{report.application.protocol_version}</dd></div></dl><table><thead><tr><th>{t("Biblioteca")}</th><th>{t("Versão")}</th><th>{t("Licença")}</th></tr></thead><tbody>{report.packages.filter(item=>item.version).map(item=><tr key={item.name}><td>{item.name}</td><td>{item.version}</td><td>{item.license}</td></tr>)}</tbody></table></>:<p>{t("Runtime indisponível.")}</p>}</details><p className="about-diagnostic-note">{t("O diagnóstico contém versões e informações do sistema. Código, dados, conexões e credenciais ficam de fora.")}</p>{error&&<p className="data-error" role="alert">{error}</p>}</div><footer><button disabled={busy||!report} onClick={()=>void action(()=>copySupportReport(),"Diagnóstico copiado.")}><Clipboard size={13}/>{t("Copiar diagnóstico")}</button><button disabled={busy||!report} onClick={()=>void action(()=>saveSupportReport(),"Diagnóstico salvo.")}><Download size={13}/>{t("Salvar diagnóstico")}</button><button onClick={onClose}>{busy&&<LoaderCircle size={13} className="spin"/>}{t("Fechar")}</button></footer></DataModal>;
}
