import { featureTranslate as t } from "./featureTranslations";
import { useLocale } from "./i18n";
import { useEffect, useRef, useState } from "react";
import { save } from "@tauri-apps/plugin-dialog";
import { Download, LoaderCircle } from "lucide-react";
import type { Data, Layout, PlotlyHTMLElement } from "plotly.js";
import { runtime, errorText, type ResultRef } from "./runtime";
import type { ChartConfig, ChartResponse, DataView } from "./dataTypes";
import "./dataActions.css";
import "./chartPanel.css";

let plotlyPromise: Promise<typeof import("plotly.js")> | undefined;
function loadPlotly() {return plotlyPromise ??= import("plotly.js-basic-dist-min").then((module) => module.default);}
export interface ChartPanelProps {sessionId: string; result: ResultRef; view?: DataView; initialConfig?: ChartConfig; onConfigChange?: (config: ChartConfig) => void; onMessage?: (message: string) => void; disabled?: boolean}
export function ChartPanel({sessionId, result, view, initialConfig, onConfigChange, onMessage, disabled}: ChartPanelProps) {
  useLocale();
  const numeric = result.columns.filter((column) => /int|float|decimal|double|number/i.test(column.dtype)).map((column) => column.name);
  const [config, setConfig] = useState<ChartConfig>(() => ({type: "bar", x_column: result.columns[0]?.name ?? "", y_columns: numeric.length ? [numeric.at(-1)!] : [result.columns.at(-1)?.name ?? ""], aggregation: "sum", nulls: "zero", palette: "default", show_grid: true, show_legend: true, show_line: true, show_markers: true, line_width: 2, marker_size: 5, line_style: "solid", bar_opacity: 94, area_opacity: 20, label_decimals: 1, live_preview: true, ...initialConfig, stacking: initialConfig?.stacking === "none" ? "grouped" : initialConfig?.stacking ?? "grouped", sort: initialConfig?.sort || "original"}));
  const [busy, setBusy] = useState(false), [exporting, setExporting] = useState(false), [selected, setSelected] = useState(false), [error, setError] = useState(""), [chart, setChart] = useState<ChartResponse>();
  const host = useRef<HTMLDivElement>(null), sequence = useRef(0), lastRequest = useRef("");
  const source = {session_id: sessionId, result_id: result.result_id, filter: view?.filter, sort: view?.sort, ...(selected && view?.scope ? {scope: view.scope} : {})};
  const requestKey = JSON.stringify({...source, config});
  useEffect(() => {sequence.current++; lastRequest.current = ""; setChart(undefined); setError(""); setBusy(false);}, [sessionId, result.result_id]);
  useEffect(() => {const node = host.current; if (!node || !chart) return; let disposed = false; let observer: ResizeObserver | undefined;
    void loadPlotly().then(async (plotly) => {if (disposed) return; await plotly.react(node, chart.figure.data as Data[], {...chart.figure.layout, autosize: true} as Partial<Layout>, {responsive: true, displaylogo: false, scrollZoom: true, modeBarButtonsToRemove: ["lasso2d", "select2d", "toImage"]}); if (disposed) return; observer = new ResizeObserver(() => {void plotly.Plots.resize(node as unknown as PlotlyHTMLElement);}); observer.observe(node);}).catch((failure) => {if (!disposed) setError(errorText(failure));});
    return () => {disposed = true; observer?.disconnect();};
  }, [chart]);
  useEffect(() => {const node = host.current; return () => {if (node) void loadPlotly().then(plotly => plotly.purge(node));};}, []);
  useEffect(() => {if (!config.live_preview || disabled || busy || !config.y_columns?.length || lastRequest.current === requestKey) return; const timer = window.setTimeout(() => {void render();}, 500); return () => window.clearTimeout(timer);}, [requestKey, busy, disabled]);
  function update(key: string, value: unknown) {const next = {...config, [key]: value}; setConfig(next); onConfigChange?.(next);}
  async function render() {if (busy || disabled || !config.y_columns?.length) return; const id = ++sequence.current; lastRequest.current = requestKey; setBusy(true); setError(""); try {const response = await runtime.request<ChartResponse>("result.chart", {...source, config}); if (id === sequence.current) setChart(response);} catch (failure) {if (id === sequence.current) setError(errorText(failure));} finally {if (id === sequence.current) setBusy(false);}}
  async function exportChart(format: "png" | "jpg" | "html" | "json") {if (!host.current || !chart) return; setExporting(true); setError(""); try {const filename = String(chart.config.title || result.variable_name || "grafico").replace(/[\\/:*?"<>|]+/g, "_"); const path = await save({defaultPath: `${filename}.${format}`, filters: [{name: format === "html" ? t("Gráfico interativo offline") : format.toUpperCase(), extensions: format === "jpg" ? ["jpg", "jpeg"] : [format]}]}); if (!path) return; const plotly = (format === "png" || format === "jpg") ? await loadPlotly() : undefined; const imageData = plotly ? await plotly.toImage(host.current, {format: "png", width: 1400, height: 850, scale: 1}) : undefined; const saved = await runtime.request<{path: string}>("result.chart_export", {...source, config: chart.config, path, format, image_data: imageData}); onMessage?.(t("Gráfico salvo: {path}", {path: saved.path}));} catch (failure) {setError(errorText(failure));} finally {setExporting(false);}}
  const numericField = (key: string, label: string, min: number, max: number) => <label key={key}>{t(label)}<input type="number" min={min} max={max} value={Number(config[key] ?? 0)} onChange={event => {const value = event.target.valueAsNumber; if (Number.isFinite(value)) update(key, Math.min(max, Math.max(min, value)));}}/></label>;
  return <div className="chart-panel"><div className="chart-settings"><div className="data-field-row"><label>{t("Tipo")}<select value={String(config.type)} onChange={(event) => update("type", event.target.value)}><option value="bar">{t("Barras")}</option><option value="line">{t("Linhas")}</option><option value="area">{t("Área")}</option><option value="scatter">{t("Dispersão")}</option><option value="pie">{t("Pizza")}</option></select></label><label>{t("Eixo X")}<select value={String(config.x_column)} onChange={(event) => update("x_column", event.target.value)}><option value="">{t("Índice")}</option>{result.columns.map((column) => <option key={column.name}>{column.name}</option>)}</select></label><label>{t("Agregação")}<select value={String(config.aggregation)} onChange={(event) => update("aggregation", event.target.value)}>{["sum", "mean", "min", "max", "count", "median"].map((name) => <option key={name} value={name}>{t(name)}</option>)}</select></label></div>
    <fieldset className="chart-series"><legend>{t("Séries Y")}</legend>{result.columns.map((column) => <label className="data-check" key={column.name}><input type="checkbox" checked={config.y_columns?.includes(column.name) ?? false} onChange={(event) => update("y_columns", event.target.checked ? [...config.y_columns ?? [], column.name] : config.y_columns?.filter((name) => name !== column.name))}/>{column.name}</label>)}</fieldset>
    <div className="data-field-row"><label>{t("Agrupar por")}<select value={String(config.group_by || "")} onChange={(event) => update("group_by", event.target.value)}><option value="">{t("Sem agrupamento")}</option>{result.columns.map((column) => <option key={column.name}>{column.name}</option>)}</select></label><label>{t("Empilhamento")}<select value={String(config.stacking)} onChange={(event) => update("stacking", event.target.value)}><option value="grouped">{t("Agrupado")}</option><option value="stacked">{t("Empilhado")}</option><option value="percent">{t("Percentual")}</option></select></label><label>{t("Nulos")}<select value={String(config.nulls)} onChange={(event) => update("nulls", event.target.value)}><option value="zero">{t("Zero")}</option><option value="drop">{t("Ignorar")}</option><option value="keep">{t("Preservar")}</option></select></label><label>{t("Ordem")}<select value={String(config.sort)} onChange={(event) => update("sort", event.target.value)}><option value="x_asc">{t("X crescente")}</option><option value="y_desc">{t("Y decrescente")}</option><option value="original">{t("Original")}</option></select></label></div>
    <div className="data-field-row"><label>{t("Título")}<input value={String(config.title || "")} onChange={(event) => update("title", event.target.value)}/></label><label>{t("Paleta")}<select value={String(config.palette)} onChange={(event) => update("palette", event.target.value)}>{["default", "categorical", "teal", "warm", "ocean"].map((name) => <option key={name} value={name}>{t(name)}</option>)}</select></label></div>
    <div className="chart-toggles">{[["show_grid", "Grade"], ["show_legend", "Legenda"], ["show_markers", "Marcadores"], ["show_data_labels", "Rótulos"], ["horizontal", "Horizontal"], ["normalize", "Normalizar %"]].map(([key, label]) => <label className="data-check" key={key}><input type="checkbox" checked={Boolean(config[key])} onChange={(event) => update(key, event.target.checked)}/>{t(label)}</label>)}</div>
    <details className="chart-advanced"><summary>{t("Cores, eixos e estilo")}</summary><div className="data-field-row"><label>{t("Rótulo X")}<input value={String(config.x_label || "")} onChange={event => update("x_label", event.target.value)}/></label><label>{t("Rótulo Y")}<input value={String(config.y_label || "")} onChange={event => update("y_label", event.target.value)}/></label><label>{t("Cores das séries")}<input value={Array.isArray(config.custom_colors) ? config.custom_colors.join(", ") : ""} placeholder={t("#5b8def, #3ddc97")} onChange={event => update("custom_colors", event.target.value.split(",").map(value => value.trim()).filter(Boolean))}/></label></div><div className="chart-color-fields">{[["background_color", "Fundo", "#101725"], ["text_color", "Texto", "#d6dce8"], ["label_color", "Rótulos", "#d6dce8"], ["grid_color", "Grade", "#253044"], ["axis_color", "Eixos", "#697b98"]].map(([key, label, fallback]) => <label key={key}><span>{t(label)}</span><input type="color" value={/^#[0-9a-f]{6}$/i.test(String(config[key])) ? String(config[key]) : fallback} onChange={event => update(key, event.target.value)}/><input aria-label={`${t(label)}: ${t("Cor")}`} value={String(config[key] || "")} placeholder={fallback} onChange={event => update(key, event.target.value)}/></label>)}</div><div className="data-field-row"><label>{t("Traço")}<select value={String(config.line_style)} onChange={event => update("line_style", event.target.value)}>{[["solid", "Contínuo"], ["dashed", "Tracejado"], ["dotted", "Pontilhado"], ["dashdot", "Traço e ponto"]].map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select></label>{numericField("line_width", "Espessura", 1, 10)}{numericField("marker_size", "Marcador", 1, 18)}{numericField("label_decimals", "Decimais dos rótulos", 0, 6)}</div><div className="data-field-row">{numericField("bar_opacity", "Opacidade das barras %", 10, 100)}{numericField("area_opacity", "Opacidade da área %", 5, 90)}</div><div className="chart-toggles">{[["show_axis_line", "Eixos"], ["show_line", "Linhas"]].map(([key, label]) => <label className="data-check" key={key}><input type="checkbox" checked={Boolean(config[key])} onChange={event => update(key, event.target.checked)}/>{t(label)}</label>)}</div></details>
    <div className="chart-actions"><button className="primary-button" disabled={busy || disabled || !config.y_columns?.length} onClick={() => void render()}>{busy && <LoaderCircle size={13} className="spin"/>}{t("Atualizar gráfico")}</button>{(["png", "jpg", "html", "json"] as const).map(format => <button key={format} disabled={!chart || busy || exporting || disabled} onClick={() => void exportChart(format)}><Download size={13}/>{format.toUpperCase()}</button>)}<label className="data-check"><input type="checkbox" checked={Boolean(config.live_preview)} onChange={event => update("live_preview", event.target.checked)}/>{t("Prévia automática")}</label>{view?.scope && <label className="data-check"><input type="checkbox" checked={selected} onChange={event => setSelected(event.target.checked)}/>{t("Somente seleção")}</label>}{chart && <small>{chart.source_rows.toLocaleString()} {t("linhas ·")} {chart.point_count} {t("pontos agregados")}{chart.bounded ? ` · ${t("limite aplicado")}` : ""}</small>}</div>{error && <p className="data-error" role="alert">{error}</p>}
  </div><div className="chart-canvas" ref={host}>{!chart && <p className="data-empty">{t("Escolha os eixos e gere o gráfico.")}</p>}</div></div>;
}
