import { featureTranslate as t } from "./featureTranslations";
import { useLocale } from "./i18n";
import { useEffect, useState } from "react";
import { Bell, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { runtime, errorText } from "./runtime";
import { DataModal } from "./DataActions";
import "./notificationSettings.css";

export interface NotificationRule {enabled: boolean; left: string; operator: string; value: string; action: string; action_value: string}
export interface NotificationConfig {enabled: boolean; title: string; message: string; color: string; rules: NotificationRule[]; channels?: {telegram?: boolean; email?: boolean}; [key: string]: unknown}
export interface NotificationContext {success?: boolean; rows?: number; blocks?: number; tab_name?: string; block_name?: string; connection?: string; database?: string; type?: string; error?: string; result_id?: string; status?:string}
interface TransportSettings {enabled: boolean; sound: boolean; success_title: string; success_message: string; error_title: string; error_message: string; telegram: {enabled: boolean; chat_id: string; configured?: boolean}; email: {enabled: boolean; host: string; port: number; use_tls: boolean; use_ssl: boolean; username: string; from_address: string; to: string; configured?: boolean}}
interface LoadedSettings {settings: TransportSettings; secrets_present: Record<string, boolean>; credential_error?: string}
export interface NotificationResult {title: string; message: string; success: boolean; color?: string; suppressed: boolean; enabled: boolean; sound: boolean; send_external: boolean; channels: {telegram: boolean; email: boolean}; deliveries?: Record<string, {status: string; error?: string}>}
export interface NotificationsDialogProps {sessionId: string; config?: NotificationConfig; context: NotificationContext; onSave: (config: NotificationConfig) => void; onDefaults?:(flags:{notifications:boolean;notificationSound:boolean})=>void; onClose: () => void}
const operators = [["equals", "Igual"], ["not_equals", "Diferente"], ["contains", "Contém"], ["not_contains", "Não contém"], ["greater_than", "Maior que"], ["less_than", "Menor que"], ["is_empty", "Vazio"], ["is_not_empty", "Não vazio"]];
export function NotificationsDialog({sessionId, config: original, context, onSave, onDefaults, onClose}: NotificationsDialogProps) {
  useLocale();
  const [tab, setTab] = useState("session"), [loaded, setLoaded] = useState<LoadedSettings>();
  const [config, setConfig] = useState<NotificationConfig>(() => ({enabled: false, title: "{{tab_name}}", message: t("{{rows}} linhas"), color: "#5b8def", rules: [], ...original}));
  const [secrets, setSecrets] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [preview, setPreview] = useState<NotificationResult>(), [message, setMessage] = useState("");
  useEffect(() => {let active = true; void runtime.request<LoadedSettings>("notifications.settings.get").then((value) => {if (active) setLoaded(value);}).catch((failure) => {if (active) setError(errorText(failure));}); return () => {active = false;};}, []);
  function updateSetting(key: keyof TransportSettings, value: unknown) {setLoaded((previous) => previous ? {...previous, settings: {...previous.settings, [key]: value}} : previous);}
  function updateChannel(channel: "telegram" | "email", key: string, value: unknown) {setLoaded((previous) => previous ? {...previous, settings: {...previous.settings, [channel]: {...previous.settings[channel], [key]: value}}} : previous);}
  function rule(index: number, key: keyof NotificationRule, value: unknown) {setConfig((previous) => ({...previous, rules: previous.rules.map((item, itemIndex) => itemIndex === index ? {...item, [key]: value} : item)}));}
  async function action(work: () => Promise<void>) {setBusy(true); setError(""); setMessage(""); try {await work();} catch (failure) {setError(errorText(failure));} finally {setBusy(false);}}
  async function save() {if (!loaded) return; const value = await runtime.request<LoadedSettings>("notifications.settings.set", {settings: loaded.settings, secrets}); setLoaded(value); setSecrets({}); onDefaults?.({notifications:value.settings.enabled,notificationSound:value.settings.sound}); onSave(config); setMessage(t("Configurações salvas."));}
  async function test(channel: string) {await save(); await runtime.request("notifications.test", {channel}); setMessage(t("Teste enviado para {channel}.", {channel}));}
  return <DataModal title={t("Notificações")} onClose={() => {if (!busy) onClose();}}><nav className="notification-tabs">{[["session", "Esta sessão"], ["defaults", "Padrões"], ["transports", "Telegram / e-mail"]].map(([id, title]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{t(title)}</button>)}</nav><div className="data-form notification-form">
    {tab === "session" && <><label className="data-check"><input type="checkbox" checked={config.enabled} onChange={(event) => setConfig({...config, enabled: event.target.checked})}/>{t("Personalizar notificações desta sessão")}</label><div className="notification-template-hint"><code>{"{{tab_name}} {{block_name}} {{rows}} {{blocks}} {{connection}} {{database}} {{type}} {{error}} {{result[0][0]}} {{variavel}}"}</code></div><label>{t("Título")}<input value={config.title} onChange={(event) => setConfig({...config, title: event.target.value})}/></label><label>{t("Mensagem")}<textarea rows={3} value={config.message} onChange={(event) => setConfig({...config, message: event.target.value})}/></label><label>{t("Cor")}<input type="color" value={/^#[0-9a-f]{6}$/i.test(config.color) ? config.color : "#5b8def"} onChange={(event) => setConfig({...config, color: event.target.value})}/></label>
      <div className="notification-rule-header"><strong>{t("Regras condicionais")}</strong><button onClick={() => setConfig({...config, rules: [...config.rules, {enabled: true, left: "{{rows}}", operator: "equals", value: "0", action: "suppress", action_value: "#d64545"}]})}><Plus size={12}/>{t("Adicionar regra")}</button></div>
      {config.rules.map((item, index) => <div className="notification-rule" key={index}><label className="data-check"><input type="checkbox" checked={item.enabled} onChange={(event) => rule(index, "enabled", event.target.checked)}/>{t("Regra")} {index + 1}</label><div className="data-field-row"><label>{t("Expressão")}<input value={item.left} onChange={(event) => rule(index, "left", event.target.value)} placeholder={t("{{rows}}")}/></label><label>{t("Operador")}<select value={item.operator} onChange={(event) => rule(index, "operator", event.target.value)}>{operators.map(([id, label]) => <option key={id} value={id}>{t(label)}</option>)}</select></label><label>{t("Valor")}<input value={item.value} onChange={(event) => rule(index, "value", event.target.value)}/></label></div><div className="notification-rule-actions"><select aria-label={t("Ação da regra")} value={item.action} onChange={(event) => rule(index, "action", event.target.value)}><option value="suppress">{t("Suprimir notificação")}</option><option value="set_color">{t("Alterar cor")}</option></select>{item.action === "set_color" && <input type="color" aria-label={t("Cor da regra")} value={/^#[0-9a-f]{6}$/i.test(item.action_value) ? item.action_value : "#d64545"} onChange={(event) => rule(index, "action_value", event.target.value)}/>}<button title={t("Remover regra")} onClick={() => setConfig({...config, rules: config.rules.filter((_, itemIndex) => itemIndex !== index)})}><Trash2 size={13}/></button></div></div>)}
      <p className="data-source">{t("Regras são avaliadas em ordem. Uma regra de supressão interrompe a avaliação e impede o aviso, o som e o envio externo.")}</p><button disabled={busy} onClick={() => void action(async () => setPreview(await runtime.request<NotificationResult>("notifications.evaluate", {session_id: sessionId, config, context})))}>{t("Pré-visualizar com o último resultado")}</button>{preview && <div className="notification-preview" style={{borderLeftColor: preview.color || "#5b8def"}}><strong>{preview.title}</strong><p>{preview.message}</p><small>{t(preview.suppressed ? "Notificação suprimida" : preview.send_external ? "Envio externo habilitado para canais configurados" : "Notificação local")}</small></div>}
    </>}
    {tab === "defaults" && loaded && <><label className="data-check"><input type="checkbox" checked={loaded.settings.enabled} onChange={(event) => updateSetting("enabled", event.target.checked)}/>{t("Habilitar notificações")}</label><label className="data-check"><input type="checkbox" checked={loaded.settings.sound} onChange={(event) => updateSetting("sound", event.target.checked)}/>{t("Som")}</label>{[["success_title", "Título de sucesso"], ["success_message", "Mensagem de sucesso"], ["error_title", "Título de erro"], ["error_message", "Mensagem de erro"]].map(([key, label]) => <label key={key}>{t(label)}<input value={String(loaded.settings[key as keyof TransportSettings])} onChange={(event) => updateSetting(key as keyof TransportSettings, event.target.value)}/></label>)}</>}
    {tab === "transports" && loaded && <><section className="notification-channel"><h4>{t("Telegram")}</h4><label className="data-check"><input type="checkbox" checked={loaded.settings.telegram.enabled} onChange={(event) => updateChannel("telegram", "enabled", event.target.checked)}/>{t("Habilitar Telegram")}</label><div className="data-field-row"><label>{t("Chat ID")}<input value={loaded.settings.telegram.chat_id} onChange={(event) => updateChannel("telegram", "chat_id", event.target.value)}/></label><label>{t("Bot token")}<input type="password" autoComplete="new-password" value={secrets.telegram_bot_token ?? ""} placeholder={t(loaded.secrets_present.telegram_bot_token ? "Token salvo · deixe vazio para manter" : "Cole o token")} onChange={(event) => setSecrets({...secrets, telegram_bot_token: event.target.value})}/></label></div><button disabled={busy} onClick={() => void action(() => test("telegram"))}>{t("Salvar e enviar teste")}</button></section>
      <section className="notification-channel"><h4>{t("E-mail SMTP")}</h4><label className="data-check"><input type="checkbox" checked={loaded.settings.email.enabled} onChange={(event) => updateChannel("email", "enabled", event.target.checked)}/>{t("Habilitar e-mail")}</label><div className="data-field-row"><label>{t("Servidor")}<input value={loaded.settings.email.host} onChange={(event) => updateChannel("email", "host", event.target.value)}/></label><label>{t("Porta")}<input type="number" min={1} max={65535} value={loaded.settings.email.port} onChange={(event) => updateChannel("email", "port", Number(event.target.value))}/></label></div><div className="notification-security"><label className="data-check"><input type="checkbox" checked={loaded.settings.email.use_tls} onChange={(event) => {updateChannel("email", "use_tls", event.target.checked); if (event.target.checked) updateChannel("email", "use_ssl", false);}}/>{t("STARTTLS")}</label><label className="data-check"><input type="checkbox" checked={loaded.settings.email.use_ssl} onChange={(event) => {updateChannel("email", "use_ssl", event.target.checked); if (event.target.checked) updateChannel("email", "use_tls", false);}}/>{t("SSL")}</label></div><div className="data-field-row"><label>{t("Usuário")}<input value={loaded.settings.email.username} onChange={(event) => updateChannel("email", "username", event.target.value)}/></label><label>{t("Senha")}<input type="password" autoComplete="new-password" value={secrets.email_password ?? ""} placeholder={t(loaded.secrets_present.email_password ? "Senha salva · deixe vazio para manter" : "Senha SMTP")} onChange={(event) => setSecrets({...secrets, email_password: event.target.value})}/></label></div><label>{t("Remetente")}<input type="email" value={loaded.settings.email.from_address} onChange={(event) => updateChannel("email", "from_address", event.target.value)}/></label><label>{t("Destinatários")}<input value={loaded.settings.email.to} onChange={(event) => updateChannel("email", "to", event.target.value)} placeholder={t("email1@exemplo.com; email2@exemplo.com")}/></label><button disabled={busy} onClick={() => void action(() => test("email"))}>{t("Salvar e enviar teste")}</button></section><p className="data-source">{t("Senhas e tokens ficam no cofre do sistema, isolados por workspace da versão Tauri.")}</p>{loaded.credential_error && <p className="data-error">{loaded.credential_error}</p>}</>}
    {!loaded && <p><LoaderCircle size={14} className="spin"/> {t("Carregando configurações…")}</p>}{error && <p className="data-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}
  </div><footer><button disabled={busy} onClick={onClose}>{t("Fechar")}</button><button className="primary-button" disabled={busy || !loaded} onClick={() => void action(save)}>{busy ? <LoaderCircle size={14} className="spin"/> : <Bell size={14}/>}{t("Salvar configurações")}</button></footer></DataModal>;
}
