import {useState} from "react";
import {DEFAULT_PREFERENCES,normalizePreferences,type Preferences} from "./preferences";
import {DEFAULT_SHORTCUTS,COMMAND_LABELS,shortcutConflicts,type Command} from "./shortcuts";
import {Modal} from "./PanelControls";
import {localizedSearch,useTranslation} from "./i18n";

const booleans=[["wordWrap","Quebra automática de linhas"],["lineNumbers","Números de linha"],["minimap","Minimapa"],["autocomplete","Autocomplete"],["aiAutocomplete","Sugestões inline da Pynia"],["maximizeFirstBlock","Abrir com primeiro bloco maximizado"]] as const;
export function SettingsDialog({preferences,shortcuts,onSave,onClose}:{preferences:Preferences;shortcuts:Record<Command,string>;onSave:(p:Preferences,s:Record<Command,string>)=>void|Promise<void>;onClose:()=>void}) {
  const {t}=useTranslation(),[p,setP]=useState(preferences),[s,setS]=useState(shortcuts),[tab,setTab]=useState("appearance"),[query,setQuery]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const field=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setP(previous=>({...previous,[key]:value}));
  const matches=(label:string)=>localizedSearch(query,label);
  const label=(text:string,children:React.ReactNode)=>matches(text)?<label key={text}>{t(text)}{children}</label>:null;
  const number=(key:keyof Preferences,text:string,min:number,max:number)=>label(text,<input type="number" min={min} max={max} value={Number(p[key])} onChange={e=>field(key,+e.target.value)}/>);
  const text=(key:keyof Preferences,description:string)=>label(description,<input value={String(p[key])} onChange={e=>field(key,e.target.value)}/>);
  const check=(key:keyof Preferences,description:string)=>matches(description)?<label className="checkbox-label" key={key}><input type="checkbox" checked={Boolean(p[key])} onChange={e=>field(key,e.target.checked)}/>{t(description)}</label>:null;
  return <Modal title={t("Configurações")} onClose={onClose} className="settings-dialog"><div className="settings-search"><input aria-label={t("Pesquisar configurações")} placeholder={t("Pesquisar configurações…")} value={query} onChange={e=>setQuery(e.target.value)}/></div><nav className="settings-tabs">{[["appearance","Aparência e editor"],["general","Geral"],["shortcuts","Atalhos"]].map(([id,title])=><button key={id} className={tab === id?"active":""} onClick={()=>setTab(id)}>{t(title)}</button>)}</nav><div className="settings-content">
    {(tab === "appearance" || query) && <div className="settings-fields">{label("Idioma",<select value={p.locale} onChange={e=>field("locale",e.target.value as Preferences["locale"])}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option></select>)}{label("Tema",<select value={p.theme} onChange={e=>field("theme",e.target.value as Preferences["theme"])}><option value="dark">{t("Escuro")}</option><option value="light">{t("Claro")}</option><option value="system">{t("Sistema")}</option></select>)}{text("uiFont","Fonte da interface")}{number("uiFontSize","Tamanho da interface",9,24)}{text("editorFont","Fonte do editor")}{number("editorFontSize","Tamanho do editor",8,32)}{text("gridFont","Fonte da grade")}{number("gridFontSize","Tamanho da grade",7,32)}{number("tabSize","Espaços por tabulação",1,8)}{booleans.map(([key,description])=>check(key,description))}</div>}
    {(tab === "general" || query) && <div className="settings-fields">{number("displayRowLimit","Limite inicial de linhas na grade",10,1000000)}{text("sharedDelimiter","Delimitador dos parâmetros compartilhados")}{number("connectionIdleSeconds","Adormecer conexões ociosas após (segundos)",0,86400)}{check("notifications","Notificar ao terminar a execução")}{check("notificationSound","Som ao terminar")}{!query && <p className="form-hint">{t("Zero mantém as conexões abertas. A conexão volta ao executar o próximo bloco.")}</p>}</div>}
    {(tab === "shortcuts" || query) && <div className="shortcut-list">{(Object.entries(COMMAND_LABELS) as [Command,string][]).filter(([,description])=>matches(description)).map(([command,description])=><label key={command}><span>{t(description)}</span><input aria-label={`${t("Atalho")} ${t(description)}`} value={s[command]} onChange={e=>setS(previous=>({...previous,[command]:e.target.value}))} onKeyDown={e=>{if(e.key === "Tab")return;if(e.ctrlKey || e.metaKey || e.altKey || /^F\d+$/.test(e.key)){e.preventDefault();setS(previous=>({...previous,[command]:[e.ctrlKey || e.metaKey?"Ctrl":"",e.altKey?"Alt":"",e.shiftKey?"Shift":"",e.key === "Return"?"Enter":e.key.length === 1?e.key.toUpperCase():e.key].filter(Boolean).join("+")}));}}}/></label>)}</div>}
    </div>{error && <p role="alert" className="form-error">{error}</p>}<footer className="modal-footer"><button className="secondary-button" onClick={()=>{setP(DEFAULT_PREFERENCES);setS(DEFAULT_SHORTCUTS);}}>{t("Restaurar padrões")}</button><span className="toolbar-spacer"/><button className="primary-button" disabled={saving} onClick={async()=>{const conflicts=shortcutConflicts(s);if(conflicts.length){setError(conflicts.join("; "));return;}if(p.sharedDelimiter.split("name").length !== 2 || !p.sharedDelimiter.split("name").every(Boolean)){setError(t("O delimitador deve conter name uma vez, com caracteres antes e depois."));return;}setSaving(true);try{await onSave(normalizePreferences(p),s);}catch(failure){setError(failure instanceof Error?failure.message:String(failure));}finally{setSaving(false);}}}>{t("Aplicar")}</button></footer></Modal>;
}
