import { featureTranslate as t } from "./featureTranslations";
import { useLocale } from "./i18n";
import { useEffect, useState } from "react";
import { Copy, ExternalLink, LoaderCircle, Search, Trash2 } from "lucide-react";
import { runtime, errorText, type ResultRef, type Variable } from "./runtime";
import { DataActions, DataModal, type DataActionsProps } from "./DataActions";
import type {DataView} from "./dataTypes";
import { ResultGrid } from "./ResultGrid";
import "./dataActions.css";

interface Inspection {name: string; type: string; preview: string; result?: ResultRef; offset: number; total_entries: number; entries: Array<{key: string; type: string; value: string}>}
export interface VariableInspectorProps extends Pick<DataActionsProps,"connectionType"|"availableConnections"|"currentConnectionId"|"currentDatabase"|"currentSchema"|"onInsertSql"|"onTableExported"|"initialExportSettings"|"onExportSettingsChange"> {sessionId: string; variables: Variable[]; disabled?: boolean; onResult: (result: ResultRef) => void; onVariables: (variables: Variable[]) => void; onInsert?: (name: string) => void}
export function VariableInspector({sessionId, variables, disabled, onResult, onVariables, onInsert, ...exportProps}: VariableInspectorProps) {
  useLocale();
  const [view,setView]=useState<DataView>();
  const [query, setQuery] = useState(""), [filter, setFilter] = useState("all");
  const [selected, setSelected] = useState<string>(), [inspection, setInspection] = useState<Inspection>();
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => {setSelected(undefined); setInspection(undefined); setError("");}, [sessionId]);
  async function inspect(name: string, offset = 0) {setBusy(true); setError(""); setSelected(name); setView(undefined); try {setInspection(await runtime.request<Inspection>("variable.inspect", {session_id: sessionId, name, offset, limit: 100}));} catch (failure) {setError(errorText(failure));} finally {setBusy(false);}}
  async function remove() {if (!selected) return; setBusy(true); setError(""); try {const value = await runtime.request<{variables: Variable[]}>("variable.delete", {session_id: sessionId, name: selected}); onVariables(value.variables); setSelected(undefined); setInspection(undefined);} catch (failure) {setError(errorText(failure));} finally {setBusy(false);}}
  const insertSql=(code:string)=>{setSelected(undefined);exportProps.onInsertSql?.(code);};
  const visible = variables.filter((variable) => (!query || `${variable.name} ${variable.type}`.toLowerCase().includes(query.toLowerCase())) && (filter === "all" || filter === "frames" && ["DataFrame", "Series", "LazyFrame"].includes(variable.type) || filter === "collections" && ["list", "tuple", "dict", "set"].includes(variable.type) || filter === "scalars" && !["DataFrame", "Series", "LazyFrame", "list", "tuple", "dict", "set"].includes(variable.type)));
  return <div className="variable-inspector"><div className="variable-filter"><label><Search size={12}/><input placeholder={t("Buscar variáveis…")} aria-label={t("Buscar variáveis")} value={query} onChange={(event) => setQuery(event.target.value)}/></label><select aria-label={t("Filtrar tipos")} value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">{t("Todos os tipos")}</option><option value="frames">{t("DataFrames / Series")}</option><option value="collections">{t("Coleções")}</option><option value="scalars">{t("Outros valores")}</option></select></div>
    <div className="variable-list">{visible.map((variable) => <button className="variable-entry" key={variable.name} disabled={disabled} title={t("Duplo clique para inspecionar")} onClick={() => onInsert?.(variable.name)} onDoubleClick={() => void inspect(variable.name)}><span><strong>{variable.name}</strong><small>{variable.type}</small></span><code>{variable.preview}</code><span className="variable-inspect-link" onClick={(event) => {event.stopPropagation(); void inspect(variable.name);}}><ExternalLink size={12}/></span></button>)}{!visible.length && <p className="data-empty">{t(variables.length ? "Nenhuma variável corresponde ao filtro." : "Execute Python ou SQL para visualizar as variáveis.")}</p>}</div>
    {selected && <DataModal title={t("Variável {name}", {name: selected})} onClose={() => {if (!busy) setSelected(undefined);}}><div className="data-form">{busy ? <p><LoaderCircle size={14} className="spin"/> {t("Carregando…")}</p> : inspection && <><p>{inspection.type}{inspection.result && ` · ${inspection.result.row_count.toLocaleString()} ${t("linhas")}`}</p>{inspection.result ? <><DataActions {...exportProps} onInsertSql={exportProps.onInsertSql ? insertSql : undefined} sessionId={sessionId} result={inspection.result} disabled={disabled || busy} view={view} hideImport hideChart onImported={(result,values)=>{onVariables(values);onResult(result);}} onChart={()=>onResult(inspection.result!)} onMessage={setError}/><div className="variable-frame-grid"><ResultGrid sessionId={sessionId} result={inspection.result} transport={runtime} onMessage={setError} copySignal={0} onViewChange={setView} dbType={exportProps.connectionType} onInsertSql={exportProps.onInsertSql ? insertSql : undefined}/></div></> : <><pre className="variable-preview">{inspection.preview}</pre>{inspection.entries.length > 0 && <table className="variable-detail-table"><thead><tr><th>{t("Chave")}</th><th>{t("Tipo")}</th><th>{t("Valor")}</th></tr></thead><tbody>{inspection.entries.map((entry, index) => <tr key={index}><td>{entry.key}</td><td>{entry.type}</td><td><code>{entry.value}</code></td></tr>)}</tbody></table>}{inspection.total_entries > 100 && <div className="variable-pagination"><button disabled={inspection.offset === 0} onClick={() => void inspect(selected, Math.max(0, inspection.offset - 100))}>{t("Anterior")}</button><span>{inspection.offset + 1}{t("–")}{Math.min(inspection.offset + 100, inspection.total_entries)} {t("de")} {inspection.total_entries}</span><button disabled={inspection.offset + 100 >= inspection.total_entries} onClick={() => void inspect(selected, inspection.offset + 100)}>{t("Próximo")}</button></div>}</>}</>}{error && <p className="data-error" role="alert">{error}</p>}</div><footer><button disabled={busy || !selected} onClick={() => void navigator.clipboard.writeText(selected ?? "").catch((failure) => setError(errorText(failure)))}><Copy size={13}/>{t("Copiar nome")}</button><button disabled={busy || !inspection} onClick={() => void navigator.clipboard.writeText(inspection?.preview ?? "").catch((failure) => setError(errorText(failure)))}><Copy size={13}/>{t("Copiar valor")}</button>{inspection?.result && <button onClick={() => {onResult(inspection.result!); setSelected(undefined);}}>{t("Abrir em resultados")}</button>}<button className="danger-button" disabled={busy} onClick={() => void remove()}><Trash2 size={13}/>{t("Remover variável")}</button></footer></DataModal>}
  </div>;
}
