import { featureTranslate as t } from "./featureTranslations";
import { useLocale } from "./i18n";
import { useEffect, useState } from "react";
import { HardDrive, LoaderCircle, RefreshCw, Trash2 } from "lucide-react";
import { runtime, errorText, type ResultRef, type Variable } from "./runtime";
import "./notificationSettings.css";

interface SnapshotSettings {enabled: boolean; restore_on_startup: boolean; max_size_mb: number}
interface Inventory {settings: SnapshotSettings; snapshots: Array<{session_id: string; saved_at: number; size_bytes: number; variables: Array<{name: string; kind: string; row_count: number; size_bytes: number}>; error?: string}>}
export interface VariableSnapshotPanelProps {sessionId: string; disabled?: boolean; onRestored: (results: ResultRef[], variables: Variable[]) => void; onMessage: (message: string) => void}
export function VariableSnapshotPanel({sessionId, disabled, onRestored, onMessage}: VariableSnapshotPanelProps) {
  useLocale();
  const [inventory, setInventory] = useState<Inventory>(), [settings, setSettings] = useState<SnapshotSettings>({enabled: false, restore_on_startup: true, max_size_mb: 50});
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [deletePending, setDeletePending] = useState(false);
  useEffect(() => {let active = true; setInventory(undefined); setDeletePending(false); void runtime.request<Inventory>("snapshot.list", {session_id: sessionId}).then((value) => {if (active) {setInventory(value); setSettings(value.settings);}}).catch((failure) => {if (active) setError(errorText(failure));}); return () => {active = false;};}, [sessionId]);
  async function action(work: () => Promise<void>) {setBusy(true); setError(""); try {await work();} catch (failure) {setError(errorText(failure));} finally {setBusy(false);}}
  async function refresh() {const value = await runtime.request<Inventory>("snapshot.list", {session_id: sessionId}); setInventory(value); setSettings(value.settings);}
  async function saveSettings() {setSettings(await runtime.request<SnapshotSettings>("snapshot.settings.set", {settings})); onMessage(t("Preferências de armazenamento salvas."));}
  async function snapshot() {await saveSettings(); const value = await runtime.request<{saved: boolean; reason?: string; size_bytes?: number; skipped?: Array<{name: string; reason: string}>}>("snapshot.save", {session_id: sessionId}); onMessage(value.saved ? `${t("Snapshot salvo.")}${value.skipped?.length ? ` ${t("{count} variáveis incompatíveis ignoradas.", {count: value.skipped.length})}` : ""}` : t("Snapshot não salvo: {reason}", {reason: value.reason ?? ""})); await refresh();}
  async function restore() {const value = await runtime.request<{restored: boolean; reason?: string; results: ResultRef[]; variables: Variable[]; skipped?: string[]}>("snapshot.restore", {session_id: sessionId}); if (value.restored) onRestored(value.results, value.variables); onMessage(value.restored ? `${t("Variáveis restauradas.")}${value.skipped?.length ? ` ${t("Variáveis já existentes preservadas: {names}", {names: value.skipped.join(", ")})}` : ""}` : t("Sem restauração: {reason}", {reason: value.reason ?? ""}));}
  const entry = inventory?.snapshots.find((item) => item.session_id === sessionId);
  return <section className="snapshot-panel"><h4><HardDrive size={14}/>{t("Armazenamento de variáveis")}</h4><label className="data-check"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({...settings, enabled: event.target.checked})}/>{t("Salvar DataFrames e Series em Parquet")}</label><label className="data-check"><input type="checkbox" checked={settings.restore_on_startup} onChange={(event) => setSettings({...settings, restore_on_startup: event.target.checked})}/>{t("Restaurar ao iniciar a sessão")}</label><label>{t("Limite por sessão (MiB)")}<input type="number" min={1} max={10000} value={settings.max_size_mb} onChange={(event) => setSettings({...settings, max_size_mb: Number(event.target.value)})}/></label><p className="data-source">{t("Desativado por padrão. O cache é isolado por workspace e preserva somente tipos compatíveis com Parquet. Variáveis já existentes são mantidas ao restaurar.")}</p><div className="snapshot-actions"><button disabled={busy} onClick={() => void action(saveSettings)}>{t("Salvar preferências")}</button><button disabled={busy || disabled || !settings.enabled} onClick={() => void action(snapshot)}>{t("Salvar agora")}</button><button disabled={busy || disabled || !settings.enabled || !entry || Boolean(entry.error)} onClick={() => void action(restore)}>{t("Restaurar")}</button><button disabled={busy} aria-label={t("Atualizar inventário")} onClick={() => void action(refresh)}><RefreshCw size={13}/></button></div>
    {entry?.error ? <p className="data-error">{entry.error}</p> : entry && <><small>{t("Salvo em")} {new Date(entry.saved_at * 1000).toLocaleString()} {t("·")} {(entry.size_bytes / 1024 / 1024).toFixed(2)} {t("MiB")}</small><table className="variable-detail-table"><thead><tr><th>{t("Variável")}</th><th>{t("Linhas")}</th><th>{t("Armazenamento")}</th></tr></thead><tbody>{entry.variables.map((variable) => <tr key={variable.name}><td>{variable.name}</td><td>{variable.row_count.toLocaleString()}</td><td>{(variable.size_bytes / 1024).toFixed(1)} {t("KiB")}</td></tr>)}</tbody></table></>}
    {entry && <button className="danger-button" disabled={busy} onClick={() => {if (!deletePending) {setDeletePending(true); return;} void action(async () => {await runtime.request("snapshot.delete", {session_id: sessionId}); setDeletePending(false); await refresh(); onMessage(t("Snapshot removido."));});}}><Trash2 size={13}/>{t(deletePending ? "Confirmar remoção do snapshot" : "Remover snapshot")}</button>}{busy && <LoaderCircle size={14} className="spin"/>}{error && <p className="data-error" role="alert">{error}</p>}
  </section>;
}
