import { featureTranslate as t } from "./featureTranslations";
import { useLocale } from "./i18n";
import { useEffect, useState } from "react";
import { Archive, Copy, Folder, LoaderCircle, Plus, RotateCcw } from "lucide-react";
import { runtime, errorText } from "./runtime";
import type { WorkspaceProfile, ProfileState } from "./nativeDrafts";
import { DataModal } from "./DataActions";
import "./workspaceProfiles.css";

interface ProfileList {active_id: string; profiles: WorkspaceProfile[]; packages_shared: boolean}
export interface WorkspaceManagerDialogProps {busy?: boolean; onSelect: (profileId: string) => Promise<void>; onClose: () => void; onMessage?: (message: string) => void}
export function WorkspaceManagerDialog({busy: runtimeBusy, onSelect, onClose, onMessage}: WorkspaceManagerDialogProps) {
  useLocale();
  const [data, setData] = useState<ProfileList>(), [selected, setSelected] = useState<string>(), [name, setName] = useState("");
  const [operation, setOperation] = useState<"create" | "rename" | "clone">(), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const [includeCredentials, setIncludeCredentials] = useState(false), [includeSnapshots, setIncludeSnapshots] = useState(true), [showArchived, setShowArchived] = useState(false);
  async function refresh() {const value = await runtime.request<ProfileList>("workspace.profiles.list", {include_archived: true}); setData(value); setSelected((previous) => previous && value.profiles.some(item => item.id === previous) ? previous : value.active_id);}
  useEffect(() => {void refresh().catch((failure) => setError(errorText(failure)));}, []);
  async function action(work: () => Promise<void>) {setLoading(true); setError(""); try {await work();} catch (failure) {setError(errorText(failure));} finally {setLoading(false);}}
  const profile = data?.profiles.find(item => item.id === selected);
  const begin = (next: "create" | "rename" | "clone") => {setOperation(next); setName(next === "create" ? "" : next === "clone" ? t("{name} cópia", {name: profile?.name ?? "Workspace"}) : profile?.name ?? ""); setIncludeCredentials(false);};
  async function save() {const value = await runtime.request<WorkspaceProfile>(`workspace.profiles.${operation}`, {profile_id: selected, name, include_credentials: includeCredentials, include_snapshots: includeSnapshots}); await refresh(); setSelected(value.id); setOperation(undefined); onMessage?.(t("Workspace salvo."));}
  return <DataModal title={t("Workspaces")} onClose={() => {if (!loading) onClose();}}><div className="workspace-manager"><aside><label className="data-check"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)}/>{t("Mostrar arquivados")}</label><div className="workspace-profile-list">{data?.profiles.filter(item => showArchived || !item.archived).map(item => <button key={item.id} className={`${selected === item.id ? "selected" : ""} ${item.archived ? "archived" : ""}`} onClick={() => {setSelected(item.id); setOperation(undefined);}}><Folder size={15}/><span>{item.name}<small>{t(item.id === data.active_id ? "Ativo" : item.archived ? "Arquivado" : "")}</small></span></button>)}</div><button onClick={() => begin("create")}><Plus size={14}/>{t("Novo workspace")}</button></aside><div className="workspace-profile-details">
    {profile && <><h3>{profile.name}</h3><code className="workspace-profile-path">{profile.path}</code><p>{t("Conexões, grupos, análises abertas, preferências, atalhos, notificações e variáveis persistidas ficam isolados neste workspace.")}</p><p className="data-source">{t("O ambiente de pacotes Python é compartilhado pela instalação Tauri. A versão PyQt mantém seu próprio workspace.")}</p>
    <div className="workspace-profile-actions"><button disabled={loading || profile.archived} onClick={() => begin("rename")}>{t("Renomear")}</button><button disabled={loading || profile.archived} onClick={() => begin("clone")}><Copy size={13}/>{t("Duplicar")}</button>{profile.archived ? <button disabled={loading} onClick={() => void action(async () => {await runtime.request("workspace.profiles.restore", {profile_id: selected}); await refresh();})}><RotateCcw size={13}/>{t("Restaurar workspace")}</button> : <button disabled={loading || profile.id === "default" || profile.id === data?.active_id} onClick={() => void action(async () => {await runtime.request("workspace.profiles.delete", {profile_id: selected}); await refresh();})}><Archive size={13}/>{t("Arquivar")}</button>}</div></>}
    {operation && <div className="workspace-profile-editor"><strong>{t(operation === "create" ? "Criar workspace" : operation === "clone" ? "Duplicar workspace" : "Renomear workspace")}</strong><label>{t("Nome")}<input autoFocus value={name} onChange={(event) => setName(event.target.value)} maxLength={100}/></label>{operation === "clone" && <><label className="data-check"><input type="checkbox" checked={includeCredentials} onChange={(event) => setIncludeCredentials(event.target.checked)}/>{t("Copiar credenciais salvas no cofre do sistema")}</label><label className="data-check"><input type="checkbox" checked={includeSnapshots} onChange={(event) => setIncludeSnapshots(event.target.checked)}/>{t("Copiar snapshots Parquet das variáveis")}</label></>}<div><button disabled={loading} onClick={() => setOperation(undefined)}>{t("Cancelar")}</button><button className="primary-button" disabled={loading || !name.trim()} onClick={() => void action(save)}>{t("Salvar workspace")}</button></div></div>}
    {runtimeBusy && <p className="data-source">{t("Finalize ou cancele as execuções antes de trocar de workspace.")}</p>}{error && <p className="data-error" role="alert">{error}</p>}{loading && <LoaderCircle size={15} className="spin"/>}
  </div></div><footer><button disabled={loading} onClick={onClose}>{t("Fechar")}</button><button className="primary-button" disabled={loading || runtimeBusy || !selected || profile?.archived || selected === data?.active_id} onClick={() => void action(async () => {await onSelect(selected!); onClose();})}>{t("Abrir workspace selecionado")}</button></footer></DataModal>;
}
export type { ProfileState };
